# Generated by Django 5.2.6 on 2025-09-07 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodytype',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='condition',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='fueltype',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pricerange',
            old_name='label',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='carcontent',
            name='body_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car.bodytype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carcontent',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car.color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carcontent',
            name='condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car.condition'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carcontent',
            name='fuel_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car.fueltype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carcontent',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='cars/photos/'),
        ),
        migrations.AlterField(
            model_name='carcontent',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='cars/photos/'),
        ),
        migrations.AlterField(
            model_name='carcontent',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='cars/photos/'),
        ),
        migrations.AlterField(
            model_name='carcontent',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='cars/photos/'),
        ),
        migrations.AlterField(
            model_name='carcontent',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='cars/photos/'),
        ),
        migrations.AlterField(
            model_name='carcontent',
            name='price_range',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car.pricerange'),
            preserve_default=False,
        ),
    ]
