# Generated by Django 5.2.6 on 2025-09-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_rename_label_bodytype_name_rename_label_color_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcontent',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
