# Generated by Django 5.2.6 on 2025-09-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_carcontent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carcontent',
            name='user',
        ),
        migrations.AddField(
            model_name='carcontent',
            name='owner_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
