# Generated by Django 5.2.6 on 2025-09-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_remove_carcontent_user_carcontent_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carcontent',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='carcontent',
            name='owner_username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
