# Generated by Django 5.2.6 on 2025-09-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_remove_carcontent_owner_id_carcontent_owner_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcontent',
            name='owner_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carcontent',
            name='owner_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
