# Generated by Django 5.2.6 on 2025-09-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_carcontent_owner_id_alter_carcontent_owner_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcontent',
            name='owner_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
