# Generated by Django 5.2.6 on 2025-09-14 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_remove_carcontent_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carcontent',
            name='owner_username',
        ),
    ]
