# Generated by Django 5.2.6 on 2025-09-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_remove_carcontent_owner_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcontent',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
