# Generated by Django 5.2.6 on 2025-09-14 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_carcontent_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carcontent',
            old_name='user',
            new_name='owner_username',
        ),
    ]
