# Generated by Django 5.2.6 on 2025-09-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_rename_user_carcontent_owner_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcontent',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
