# Generated by Django 5.2.6 on 2025-09-17 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_carcontent_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carcontent',
            name='video',
        ),
    ]
