# Generated by Django 5.2.6 on 2025-09-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_remove_carcontent_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carcontent',
            name='video_url',
        ),
        migrations.AddField(
            model_name='carcontent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='cars/videos/'),
        ),
    ]
